apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a-container
        image: 'applicationa:latest'
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: '100m'
            memory: '512Mi'
      restartPolicy: 'Always'

---
apiVersion: v1
kind: Service
metadata:
  name: app-a-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80